// Methods
export const METHOD_GET = 'GET';
export const METHOD_POST = 'POST';
export const METHOD_DELETE = 'DELETE';
export const METHOD_PUT = 'PUT';

// Get Todos
export const GET_ALL_TODOS_PENDING = 'GET_ALL_TODOS_PENDING';
export const GET_ALL_TODOS_FULFILLED = 'GET_ALL_TODOS_FULFILLED';
export const GET_ALL_TODOS_REJECTED = 'GET_ALL_TODOS_REJECTED';

// Post Todos
export const POST_TODOS_PENDING = 'POST_TODOS_PENDING';
export const POST_TODOS_FULFILLED = 'POST_TODOS_FULFILLED';
export const POST_TODOS_REJECTED = 'POST_TODOS_REJECTED';

// Put Todos
export const PUT_TODOS_PENDING = 'PUT_TODOS_PENDING';
export const PUT_TODOS_FULFILLED = 'PUT_TODOS_FULFILLED';
export const PUT_TODOS_REJECTED = 'PUT_TODOS_REJECTED';

// Delete Todos
export const DELETE_TODOS_PENDING = 'DELETE_TODOS_PENDING';
export const DELETE_TODOS_FULFILLED = 'DELETE_TODOS_FULFILLED';
export const DELETE_TODOS_REJECTED = 'DELETE_TODOS_REJECTED';
